cpus: 2
artifact_dir: artifacts
input_dir: ./
meta:
  id: study
study_name: study
study_type: rnaseq
study_abundance_type: counts
report_file: !!org.codehaus.groovy.runtime.GStringImpl {}
report_title: null
report_author: null
report_contributors: null
report_description: null
report_scree: true
report_round_digits: 4
observations_type: sample
observations_id_col: sample
observations_name_col: null
features: matrix_as_anno.feature_metadata.tsv
features_type: gene
features_id_col: gene_id
features_name_col: gene_name
features_metadata_cols: gene_id,gene_name,gene_biotype
features_gtf_feature_type: transcript
features_gtf_table_first_field: gene_id
filtering_min_samples: 1.0
filtering_min_abundance: 1.0
filtering_min_proportion: null
filtering_grouping_var: null
filtering_min_proportion_not_na: 0.5
filtering_min_samples_not_na: null
exploratory_main_variable: auto_pca
exploratory_clustering_method: ward.D2
exploratory_cor_method: spearman
exploratory_n_features: 500
exploratory_whisker_distance: 1.5
exploratory_mad_threshold: -5
exploratory_assay_names: raw,normalised,variance_stabilised
exploratory_final_assay: variance_stabilised
exploratory_log2_assays: raw,normalised
exploratory_palette_name: Set1
differential_file_suffix: null
differential_feature_id_column: gene_id
differential_feature_name_column: gene_name
differential_fc_column: log2FoldChange
differential_pval_column: pvalue
differential_qval_column: padj
differential_min_fold_change: 2.0
differential_max_pval: 1.0
differential_max_qval: 0.05
differential_foldchanges_logged: true
differential_palette_name: Set1
differential_subset_to_contrast_samples: false
deseq2_test: Wald
deseq2_fit_type: parametric
deseq2_sf_type: ratio
deseq2_min_replicates_for_replace: 7
deseq2_use_t: false
deseq2_lfc_threshold: 0
deseq2_alt_hypothesis: greaterAbs
deseq2_independent_filtering: true
deseq2_p_adjust_method: BH
deseq2_alpha: 0.1
deseq2_minmu: 0.5
deseq2_vs_method: vst
deseq2_shrink_lfc: true
deseq2_cores: 1
deseq2_vs_blind: true
deseq2_vst_nsub: 1000
gene_sets_files: null
observations: samplesheet.sample_metadata.tsv
raw_matrix: salmon.merged.gene_counts.assay.tsv
normalised_matrix: all.normalised_counts.tsv
variance_stabilised_matrix: all.vst.tsv
contrasts_file: contrasts.contrasts_file.tsv
versions_file: collated_versions.yml
logo: nf-core-differentialabundance_logo_light.png
css: nf-core_style.css
citations: CITATIONS.md
